//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagazynBazaProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magazyn
    {
        public int ID { get; set; }
        public string Nazwa { get; set; }
        public string Kategoria { get; set; }
        public string Producent { get; set; }
        public int Ilość { get; set; }
        public string Samochód { get; set; }
        public string Silnik { get; set; }
        public decimal Cena { get; set; }
    }
}
